general.import = [
    "~/.config/alacritty/themes/catppuccin.toml"
]

[window]
# opacity= 0.98
# decorations="none"

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 120
lines = 80

[colors.primary]
background = "#000000"


[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
style = "Block"

[terminal.shell]
program = "/opt/homebrew/bin/tmux" # <- Set your path
args = ["new-session", "-A", "-D", "-s", "main"]

[keyboard]
bindings = [
    { key = "H", mods = "Control|Shift", chars = "\uE000" },
    { key = "J", mods = "Control|Shift", chars = "\uE001" },
    { key = "K", mods = "Control|Shift", chars = "\uE002" },
    { key = "L", mods = "Control|Shift", chars = "\uE003" },
    { key = ";", mods = "Control", chars = "&" }
]

[terminal]
osc52 = "CopyPaste"
