sudo ln -s /mnt/x /x
sudo ln -s /mnt/f /f
sudo ln -s /mnt/x/Lectra ~/work
sudo ln -s /mnt/x/Stefan ~/personal
sudo ln -s ~/dotfiles/dunst ~/.config/dunst
sudo ln -s ~/dotfiles/ulauncher ~/.config/ulauncher
sudo ln -s ~/dotfiles/i3 ~/.config/i3
sudo ln -s ~/dotfiles/i3/i3status ~/.config/i3status
sudo ln -s ~/dotfiles/i3/i3-layout-manager ~/.config/i3-layout-manager
sudo ln -s ~/dotfiles/i3/i3blocks/.i3blocks.conf ~/.i3blocks.conf
sudo ln -s ~/dotfiles/scripts ~/scripts
sudo ln -s ~/dotfiles/lsd ~/.config/lsd
sudo ln -s ~/dotfiles/gnome/gtk.css ~/.config/gtk-3.0/gtk.css
sudo ln -s ~/dotfiles/zsh/custom/custom-agnoster.zsh-theme ~/.oh-my-zsh/themes/custom-agnoster.zsh-theme
sudo ln -s ~/dotfiles/zsh/custom/custom-fox.zsh-theme ~/.oh-my-zsh/themes/ccustom-fox.zsh-theme
sudo ln -s ~/dotfiles/flameshot ~/.config/flameshot
sudo ln -s ~/dotfiles/alacritty ~/.config/alacritty
sudo ln -s ~/dotfiles/lazygit ~/.config/lazygit
sudo ln -s ~/dotfiles/zsh/.profile ~/.profile
sudo ln -s ~/dotfiles/zsh/.zshenv ~/.zshenv
sudo ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc
sudo ln -s ~/dotfiles/nvim ~/.config/nvim
sudo ln -s ~/dotfiles/misc/.xprofile ~/.xprofile
sudo ln -s ~/dotfiles/stern ~/.config/stern
sudo ln -s ~/dotfiles/k9s ~/.config/k9s
sudo ln -s ~/dotfiles/bat ~/.config/bat
sudo ln -s ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
sudo ln -s ~/dotfiles/tmux/resurrect ~/.tmux/resurrect
sudo ln -s ~/dotfiles/lazygitconfig ~/.config/lazygit
