k9s:
  cluster: aks19-EUW-prod-main
  namespace:
    active: apogy-digital-platform
    lockFavorites: false
    favorites:
    - apogy-digital-platform
    - default
  view:
    active: ns
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
